// Ported from the checked-in Codama client. Field and account order is the wire ABI.
const accountLayouts = <String, List<(String, String, int)>>{
  'market': [
    ('discriminator', 'bytes', 8),
    ('baseMint', 'address', 32),
    ('quoteMint', 'address', 32),
    ('baseFlow', 'u128', 1),
    ('quoteFlow', 'u128', 1),
    ('minimumBaseDepositAtoms', 'u64', 1),
    ('minimumQuoteDepositAtoms', 'u64', 1),
    ('startSlot', 'u64', 1),
    ('openPositions', 'u64', 1),
    ('accumulatedBaseFees', 'u64', 1),
    ('accumulatedQuoteFees', 'u64', 1),
    ('id', 'u32', 1),
    ('feeBps', 'u8', 1),
    ('unhealthyLiquidityFeeBps', 'u8', 1),
    ('slotsUntilDebt', 'u8', 1),
    ('liquidityAmplification', 'u8', 1),
    ('kind', 'u8', 1),
    ('isPaused', 'u8', 1),
    ('bump', 'u8', 1),
    ('makerAuthority', 'address', 32),
    ('pendingMakerAuthority', 'address', 32),
    ('quoteOperator', 'address', 32),
    ('padding0', 'bytes', 5),
    ('makerBaseInventory', 'i128', 1),
    ('makerQuoteInventory', 'i128', 1),
    ('makerBaseFlowAtoms', 'u64', 1),
    ('makerQuoteFlowAtoms', 'u64', 1),
    ('makerBasePerQuoteSnapshot', 'u128', 1),
    ('makerQuotePerBaseSnapshot', 'u128', 1),
    ('makerSlotsWithoutTradeSnapshot', 'u32', 1),
    ('padding1', 'bytes', 4),
    ('makerLastUpdateSlot', 'u64', 1),
    ('bookkeeping', 'bookkeepingState', 128),
  ],
  'tradePosition': [
    ('discriminator', 'bytes', 8),
    ('authority', 'address', 32),
    ('market', 'address', 32),
    ('payer', 'address', 32),
    ('operator', 'address', 32),
    ('baseReceiver', 'address', 32),
    ('quoteReceiver', 'address', 32),
    ('flow', 'u128', 1),
    ('bookkeepingSnapshot', 'u128', 1),
    ('amount', 'u64', 1),
    ('inactiveRefund', 'u64', 1),
    ('startSlot', 'u64', 1),
    ('lastUpdateSlot', 'u64', 1),
    ('pausedAtSlot', 'u64', 1),
    ('swappedAmountAtSnapshot', 'u64', 1),
    ('withdrawnAmount', 'u64', 1),
    ('remainingSlots', 'u32', 1),
    ('slotsWithoutTradesSnapshot', 'u32', 1),
    ('id', 'u32', 1),
    ('feeBpsAtSubmission', 'u8', 1),
    ('side', 'u8', 1),
    ('bump', 'u8', 1),
    ('padding', 'bytes', 9),
  ],
  'marketInterval': [
    ('discriminator', 'bytes', 8),
    ('market', 'address', 32),
    ('index', 'u64', 1),
    ('payer', 'address', 32),
    ('slotsWithoutTradesSnapshot', 'u32', 16),
    ('openPositions', 'u32', 1),
    ('bump', 'u8', 1),
    ('padding', 'bytes', 3),
    ('baseExits', 'u128', 16),
    ('quoteExits', 'u128', 16),
    ('basePerQuoteSnapshot', 'u128', 16),
    ('quotePerBaseSnapshot', 'u128', 16),
  ],
  'closePositionEvent': [
    ('discriminator', 'bytes', 8),
    ('market', 'address', 32),
    ('positionAddress', 'address', 32),
    ('positionAuthority', 'address', 32),
    ('baseReceiver', 'address', 32),
    ('quoteReceiver', 'address', 32),
    ('depositAmount', 'u64', 1),
    ('swappedAmount', 'u64', 1),
    ('remainingAmount', 'u64', 1),
    ('feeAmount', 'u64', 1),
    ('startSlot', 'u64', 1),
    ('endSlot', 'u64', 1),
    ('side', 'u8', 1),
  ],
  'tradeFeeCollectedEvent': [
    ('discriminator', 'bytes', 8),
    ('market', 'address', 32),
    ('position', 'address', 32),
    ('mint', 'address', 32),
    ('totalFee', 'u64', 1),
    ('makerFee', 'u64', 1),
    ('protocolFee', 'u64', 1),
  ],
  'bookkeepingState': [
    ('basePerQuote', 'u128', 1),
    ('previousBasePerQuote', 'u128', 1),
    ('windowBasePerQuote', 'u128', 1),
    ('quotePerBase', 'u128', 1),
    ('previousQuotePerBase', 'u128', 1),
    ('windowQuotePerBase', 'u128', 1),
    ('lastUpdateSlot', 'u64', 1),
    ('previousUpdateSlot', 'u64', 1),
    ('windowStartSlot', 'u64', 1),
    ('slotsWithoutTrade', 'u32', 1),
    ('padding', 'bytes', 4),
  ],
};
const accountDiscriminators = <String, List<int>>{
  'closePositionEvent': [198, 217, 115, 95, 191, 120, 142, 137],
  'tradeFeeCollectedEvent': [69, 74, 9, 89, 150, 217, 29, 39],
  'market': [219, 190, 213, 55, 0, 227, 198, 154],
  'tradePosition': [37, 143, 119, 76, 200, 164, 122, 202],
  'marketInterval': [227, 40, 58, 114, 183, 178, 213, 116],
};
const instructionLayouts = <String, List<(String, int)>>{
  'submitOrder': [
    ('id', 4),
    ('futureIndex', 8),
    ('referenceIndex', 8),
    ('amount', 8),
    ('duration', 4),
  ],
  'pauseTradePosition': [('referenceIndex', 8)],
  'unpauseTradePosition': [('futureIndex', 8), ('referenceIndex', 8)],
  'withdrawSwapped': [('referenceIndex', 8)],
  'authorityCloseTradePosition': [('referenceIndex', 8)],
  'closeMarketInterval': [('referenceIndex', 8)],
};
const instructionAccounts = <String, List<(String, bool)>>{
  'submitOrder': [
    ('authority', true),
    ('payer', true),
    ('operator', false),
    ('baseReceiver', false),
    ('quoteReceiver', false),
    ('authorityAta', true),
    ('mint', false),
    ('market', true),
    ('tradePosition', true),
    ('vault', true),
    ('currentInterval', true),
    ('previousInterval', true),
    ('futureInterval', true),
    ('tokenProgram', false),
    ('associatedTokenProgram', false),
    ('systemProgram', false),
  ],
  'pauseTradePosition': [
    ('signer', true),
    ('baseMint', false),
    ('quoteMint', false),
    ('market', true),
    ('tradePosition', true),
    ('futureInterval', true),
    ('currentInterval', true),
    ('previousInterval', true),
    ('baseTokenProgram', false),
    ('quoteTokenProgram', false),
    ('associatedTokenProgram', false),
    ('systemProgram', false),
  ],
  'unpauseTradePosition': [
    ('signer', true),
    ('baseMint', false),
    ('quoteMint', false),
    ('market', true),
    ('tradePosition', true),
    ('oldInterval', true),
    ('futureInterval', true),
    ('currentInterval', true),
    ('previousInterval', true),
    ('baseTokenProgram', false),
    ('quoteTokenProgram', false),
    ('associatedTokenProgram', false),
    ('systemProgram', false),
  ],
  'withdrawSwapped': [
    ('signer', true),
    ('programConfig', false),
    ('receiver', true),
    ('mint', false),
    ('receiverTokenAccount', true),
    ('market', true),
    ('tradePosition', true),
    ('vault', true),
    ('currentInterval', true),
    ('previousInterval', true),
    ('tokenProgram', false),
    ('associatedTokenProgram', false),
    ('systemProgram', false),
  ],
  'authorityCloseTradePosition': [
    ('authority', true),
    ('programConfig', false),
    ('payer', true),
    ('baseReceiver', false),
    ('quoteReceiver', false),
    ('baseMint', false),
    ('quoteMint', false),
    ('receiverBaseTokenAccount', true),
    ('receiverQuoteTokenAccount', true),
    ('market', true),
    ('tradePosition', true),
    ('baseVault', true),
    ('quoteVault', true),
    ('futureInterval', true),
    ('currentInterval', true),
    ('previousInterval', true),
    ('baseTokenProgram', false),
    ('quoteTokenProgram', false),
    ('associatedTokenProgram', false),
    ('systemProgram', false),
  ],
  'closeMarketInterval': [
    ('signer', true),
    ('payer', true),
    ('marketInterval', true),
    ('market', true),
    ('currentInterval', true),
    ('previousInterval', true),
    ('systemProgram', false),
  ],
};
const instructionDiscriminators = <String, List<int>>{
  'submitOrder': [230, 150, 200, 53, 92, 208, 109, 108],
  'pauseTradePosition': [93, 3, 178, 173, 29, 165, 4, 9],
  'unpauseTradePosition': [212, 116, 103, 81, 196, 132, 86, 153],
  'withdrawSwapped': [196, 235, 42, 103, 30, 197, 174, 94],
  'authorityCloseTradePosition': [122, 9, 159, 161, 73, 91, 188, 216],
  'closeMarketInterval': [220, 103, 218, 126, 157, 102, 70, 29],
};
